version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_v1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_nestjs
      MYSQL_USER: Juan_crud
      MYSQL_PASSWORD: root123
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"